### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by snoopspy** [real2u2l8/send-arp#1]
https://user-images.githubusercontent.com/4080232/184646167-95d32c68-bd69-4634-9549-643672273be4.mp4

실행을 하면 Segmentation fault error가 뜨면서 정상적인 공격이 이루어지지 않고 있습니다. 문제를 해결하시기 바랍니다.

**Comment by real2u2l8** [comment]
@snoopspy 

해당 버그를 잡았습니다..

하지만,
main.cpp 중 124째 줄(senderIP의 Mac 주소를 가져오기 위한 Arp Reply 캡처 부분) While문에서 코드가 빠져 나오지 않아

결과적으로는 Infective ARP Reply가 전송 되지 않습니다..

아무리 생각해보고 코드를 보아도 해결 되지 않네요..

**Comment by real2u2l8** [comment]
> 2022-08-15.22-36-59.mp4 
> 실행을 하면 Segmentation fault error가 뜨면서 정상적인 공격이 이루어지지 않고 있습니다. 문제를 해결하시기 바랍니다.

해결 했습니다~!!! 이슈는 close 하겠습니다!
감사합니다!
